
name: Local Test
on: [push]
jobs:
  test-claude-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Claude Code with direct prompt
        uses: ./
        with:
          prompt: "What is 2 + 2?"
          allowed_tools: ""
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
